name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    env:
      DEVELOPER_DIR: /Applications/Xcode_12_beta.app/Contents/Developer


    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      run: swift test
